version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stopcont.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/startcontainer.sh
      timeout: 300
      runas: root
